service: birdie-backend
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  memorySize: 128
useDotenv: true
functions:
  app:
    handler: app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true 
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true